### ISSUE TITLE
Pip install -r requirements.txt fails

### ISSUE THREAD

**Issue by enricorotundo** [Erlemar/wheat#7]
Hi there I've tried to pip install the dependencies but I get the following error both on Ubuntu 18 and macOS `ERROR: Could not find a version that satisfies the requirement pytorch_lightning==0.8.0`. Any idea? Did you use python2?

**Comment by Erlemar** [comment]
Hello!

It seems that this version is not available any more on pip, not sure what is the reason for it.
The nearest available version is 0.8.1 - try to use it, there should be no difference in the code itself.
